create_product:
    path: /product
    controller: App\Controller\ProductController::create
    methods:  [POST]
modify_product:
    path: /product/{productId}
    controller: App\Controller\ProductController::update
    methods:  [PUT]
list_product:
    path: /products
    controller: App\Controller\ProductController::list
    methods:  [GET]
product_details:
    path: /product/{productId}
    controller: App\Controller\ProductController::details
    methods:  [GET]
delete_product:
    path: /product/{productId}
    controller: App\Controller\ProductController::delete
    methods:  [DELETE]
product_catelog:
    path: /catelog
    controller: App\Controller\ProductController::catelog
    methods:  [GET]

create_discount:
    path: /discount
    controller: App\Controller\DiscountController::create
    methods:  [POST]
modify_discount:
    path: /discount/{discountId}
    controller: App\Controller\DiscountController::update
    methods:  [PUT]
list_discount:
    path: /discounts
    controller: App\Controller\DiscountController::list
    methods:  [GET]
delete_discount:
    path: /discount/{discountId}
    controller: App\Controller\DiscountController::delete
    methods:  [DELETE]

create_bundle:
    path: /bundle
    controller: App\Controller\BundleController::create
    methods:  [POST]
update_bundle:
    path: /bundle/{bundleId}
    controller: App\Controller\BundleController::update
    methods:  [PUT]
bundle_list:
    path: /bundles
    controller: App\Controller\BundleController::list
    methods:  [GET]
delete_bundle:
    path: /bundle/{bundleId}
    controller: App\Controller\BundleController::delete
    methods:  [DELETE]

place_order:
    path: /order
    controller: App\Controller\OrderController::place
    methods:  [POST]